# Generated by Django 3.2.7 on 2021-10-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacultiesT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=5)),
                ('departments', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FriendsT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user1', models.IntegerField()),
                ('user2', models.IntegerField()),
                ('applied', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='default/')),
                ('n1', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('department', models.IntegerField()),
                ('course', models.IntegerField()),
                ('bio', models.CharField(max_length=400)),
                ('is_filled', models.BooleanField()),
                ('rating', models.IntegerField()),
                ('accesss', models.IntegerField()),
                ('username', models.CharField(max_length=20)),
                ('faculty', models.IntegerField()),
                ('trusted', models.IntegerField()),
                ('is_moderator', models.BooleanField()),
                ('is_curator', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('image', models.ImageField(upload_to='photo_path')),
                ('folder', models.CharField(max_length=10)),
            ],
        ),
    ]
