# Generated by Django 3.2.7 on 2021-09-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('side1', models.IntegerField()),
                ('side2', models.IntegerField()),
                ('accepted', models.BooleanField()),
            ],
        ),
    ]
