# Generated by Django 3.2.7 on 2021-09-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0002_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
