# Generated by Django 3.2.7 on 2021-09-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0003_auto_20210905_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('department', models.IntegerField()),
                ('course', models.IntegerField()),
                ('faculty', models.IntegerField()),
                ('username', models.CharField(max_length=20)),
                ('is_moderator', models.BooleanField()),
                ('is_curator', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PesonT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('department', models.IntegerField()),
                ('course', models.IntegerField()),
                ('bio', models.CharField(max_length=400)),
                ('is_filled', models.BooleanField()),
                ('rating', models.IntegerField()),
                ('accesss', models.IntegerField()),
                ('username', models.CharField(max_length=20)),
                ('faculty', models.IntegerField()),
                ('trusted', models.IntegerField()),
                ('is_moderator', models.BooleanField()),
                ('is_curator', models.BooleanField()),
            ],
        ),
    ]
