# Generated by Django 3.2.7 on 2021-09-15 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0004_people_person_pesont'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PesonT',
            new_name='PersonT',
        ),
    ]
