# Generated by Django 3.2.7 on 2021-09-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0005_rename_pesont_persont'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=5)),
                ('departments', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FriendsT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user1', models.IntegerField()),
                ('user2', models.IntegerField()),
                ('applied', models.BooleanField()),
            ],
        ),
    ]
