# Generated by Django 3.2.7 on 2021-09-30 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0008_auto_20210930_1230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
