# Generated by Django 3.2.7 on 2021-09-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0009_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
    ]
