# Generated by Django 3.2.7 on 2021-09-30 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0010_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
    ]
