# Generated by Django 3.2.7 on 2021-09-30 13:55

import beta.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0012_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('image', models.ImageField(upload_to=beta.models.UserImage.photo_path)),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=beta.models.Image.photo_path),
        ),
    ]
